alias em='emacs'
alias emn="emacs -nw"
alias sudo='sudo '
alias doas='doas '
alias e="pkg install"
alias es="pkg search"
alias man="info"
alias ff="firefox"
alias sl="ls"
alias ll="ls"
alias dr='emacs --eval "(dirvish)"'
